#!/bin/sh
# We don't have a Debian package for python3-pygame, so we're building it
# from scratch.
#
# The package dependencies come from examining the dependencies of
# python-pygame (the Python 2 version), adding dev packages as necessary
# to support the build, and examining the pygame configuraiton output to
# ensure that all Pygame build dependencies were present.
sudo apt-get update
sudo apt-get install -qy python3 python3-dev python3-pip python3-numpy \
    git mercurial \
    libsdl-console libsdl-console-dev \
    libsdl-image1.2 libsdl-image1.2-dev \
    libsdl-mixer1.2 libsdl-mixer1.2-dev \
    libsdl-ttf2.0-0 libsdl-ttf2.0-dev \
    libsdl1.2debian libsdl1.2-dev \
    libsmpeg0 libsmpeg-dev \
    libportmidi0 libportmidi-dev \
    libavformat54 libavformat-dev \
    libswscale2 libswscale-dev \
    libx11-6 timidity fonts-freefont-ttf libfreetype6-dev
sudo pip3 install hg+http://bitbucket.org/pygame/pygame
